### ISSUE TITLE
Advertisement is breaking page

### ISSUE THREAD

**Issue by luckydonald** [danog-clients/alessandracartocci.com#11]
<img width="1299" alt="Screenshot 2020-01-06 at 17 57 44" src="https://user-images.githubusercontent.com/2737108/71833825-14d27100-30ae-11ea-8298-55a5e47604de.png">

**Comment by danog** [comment]
no lol, that trash website isn't mine anymore, she dumped me for a wordpress n00b

**Comment by danog** [comment]
shit.daniil.it mirror
